# Generated by Django 3.2.5 on 2021-07-29 15:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data da Aposta')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'ordering': ['-created_at'],
            },
        ),
    ]
